# Configuration for web scraping mode
# Copy of agent_config.yaml with web scraping enabled

# Center & radius
center_address: "37 Warren Street, New York, NY 10007"
radius_miles: 50

# Filters
price_usd_max: 5000000
earnings_multiple_max: 5.0
reason_for_sale_whitelist: ["retirement","succession","owner aging","transition after long tenure"]
exclude_categories: ["restaurants","bars","cleaning services","high-turnover retail","salons/spas","gyms"]
visit_frequency_allowlist: ["weekly","monthly"]
employee_owned_preferred: true

# Data Sources - Web scraping enabled for testing
sources:
  # Email alerts (disabled for pure web scraping test)
  email_alerts:
    enabled: false
    imap_label: "biz-acq/alerts"
    lookback_days: 7
  
  # Web scraping (enabled)
  web_scraping:
    enabled: true
    
    bizbuysell:
      enabled: true
      search_url: "https://www.bizbuysell.com/businesses-for-sale/"
      max_pages: 2  # Start small for testing
      delay_seconds: 3  # Be respectful
    
    bizquest:
      enabled: true
      search_url: "https://www.bizquest.com/businesses-for-sale/"
      max_pages: 2
      delay_seconds: 3
    
    dealstream:
      enabled: false  # Can enable later
      search_url: "https://www.dealstream.com/opportunities/"
      max_pages: 2
      delay_seconds: 3

# Outputs
outputs:
  json_path: "data/web_scraping_results.json"
  markdown_path: "data/web_scraping_results.md"
  rejects_path: "data/web_scraping_rejects.csv"
